### ISSUE TITLE
"to Make Sure" in the Appendix misses the point

### ISSUE THREAD

**Issue by revelutions** [associationforsoftwaretesting/navigating#2]
This paragraph starts with 'Testing is an information gathering process.' The remainder explains that we share our findings, how that information is used or not, etc.  

Instead, it's much more important to make the point, that we are searching for 'unknown unknowns'.  It's also important to talk about the challenges in testing.  We are trying to understand user's mental models, how they perceive software, how complex systems interact, how to consider multiple variables, etc.  Given that background, we cannot be 'sure'.  

The ideas currently described are useful.  However, they need to come after explaining th challenge of testing.  The project and stakeholder related challenges come later.

**Comment by qahiccupps** [comment]
Thank you. I think that your main point is already captured in this sentence: "There can be reducing amounts of uncertainty as more is learned ... but there is no being sure."
